apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  namespace: jenkins
  labels:
    app: jenkins
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
