apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-read-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-secrets
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: default
