apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-secrets
rules:
  - apiGroups:
    - ''
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-pods
rules:
  - apiGroups:
    - ''
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - watch
      - list
      - exec
